export interface BoardGame {
  id: number;
  name: string;
  description: string;
  minPlayers: number;
  maxPlayers: number;
  minAge: number;
  playTime: string;
  categories: string[];
  rating: number;
  image: string;
  year: number;
}

export const categories = [
  "Strategiczne",
  "Rodzinne",
  "Imprezowe",
  "Kooperacyjne",
  "Ekonomiczne",
  "Przygodowe",
  "Karciane",
  "Wojenne",
  "Abstrakcyjne",
  "Dedukcyjne",
] as const;

export const games: BoardGame[] = [
  {
    id: 1,
    name: "Catan",
    description: "Klasyczna gra o osadnikach budujących kolonie na wyspie Catan. Zbieraj surowce, handluj i rozbudowuj swoją osadę.",
    minPlayers: 3,
    maxPlayers: 4,
    minAge: 10,
    playTime: "60-120 min",
    categories: ["Strategiczne", "Rodzinne", "Ekonomiczne"],
    rating: 4.2,
    image: "/images/catan.jpg",
    year: 1995,
  },
  {
    id: 2,
    name: "Ticket to Ride: Europa",
    description: "Buduj trasy kolejowe przez Europę, zbieraj karty wagonów i realizuj trasy łączące odległe miasta.",
    minPlayers: 2,
    maxPlayers: 5,
    minAge: 8,
    playTime: "30-60 min",
    categories: ["Rodzinne", "Strategiczne"],
    rating: 4.5,
    image: "/images/ticket-to-ride.jpg",
    year: 2004,
  },
  {
    id: 3,
    name: "Pandemic",
    description: "Kooperacyjna gra, w której gracze jako zespół specjalistów powstrzymują globalne epidemie.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 8,
    playTime: "45 min",
    categories: ["Kooperacyjne", "Strategiczne"],
    rating: 4.6,
    image: "/images/pandemic.jpg",
    year: 2008,
  },
  {
    id: 4,
    name: "Carcassonne",
    description: "Układaj kafelki i buduj średniowieczny krajobraz z miastami, drogami i klasztorami.",
    minPlayers: 2,
    maxPlayers: 5,
    minAge: 7,
    playTime: "30-45 min",
    categories: ["Rodzinne", "Strategiczne", "Abstrakcyjne"],
    rating: 4.3,
    image: "/images/carcassonne.jpg",
    year: 2000,
  },
  {
    id: 5,
    name: "Dixit",
    description: "Kreatywna gra z pięknymi ilustracjami, gdzie opowiadasz historie i zgadujesz karty innych graczy.",
    minPlayers: 3,
    maxPlayers: 6,
    minAge: 8,
    playTime: "30 min",
    categories: ["Imprezowe", "Rodzinne", "Karciane"],
    rating: 4.4,
    image: "/images/dixit.jpg",
    year: 2008,
  },
  {
    id: 6,
    name: "Splendor",
    description: "Zostań kupcem renesansowym, zbieraj kamienie szlachetne i buduj swoje handlowe imperium.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 10,
    playTime: "30 min",
    categories: ["Strategiczne", "Ekonomiczne"],
    rating: 4.3,
    image: "/images/splendor.jpg",
    year: 2014,
  },
  {
    id: 7,
    name: "Azul",
    description: "Abstrakcyjna gra o układaniu pięknych kafelków portugalskich azulejos.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 8,
    playTime: "30-45 min",
    categories: ["Abstrakcyjne", "Rodzinne"],
    rating: 4.5,
    image: "/images/azul.jpg",
    year: 2017,
  },
  {
    id: 8,
    name: "Codenames",
    description: "Gra słowna dla dwóch drużyn - podawaj wskazówki i odgaduj tajnych agentów.",
    minPlayers: 4,
    maxPlayers: 8,
    minAge: 14,
    playTime: "15 min",
    categories: ["Imprezowe", "Dedukcyjne"],
    rating: 4.7,
    image: "/images/codenames.jpg",
    year: 2015,
  },
  {
    id: 9,
    name: "7 Cudów Świata",
    description: "Rozwijaj starożytną cywilizację przez trzy epoki, budując jeden z cudów świata.",
    minPlayers: 2,
    maxPlayers: 7,
    minAge: 10,
    playTime: "30 min",
    categories: ["Strategiczne", "Karciane"],
    rating: 4.4,
    image: "/images/7-wonders.jpg",
    year: 2010,
  },
  {
    id: 10,
    name: "Terraformowanie Marsa",
    description: "Przekształć Marsa w planetę nadającą się do życia, zarządzając korporacją kosmiczną.",
    minPlayers: 1,
    maxPlayers: 5,
    minAge: 12,
    playTime: "120 min",
    categories: ["Strategiczne", "Ekonomiczne"],
    rating: 4.8,
    image: "/images/terraforming-mars.jpg",
    year: 2016,
  },
  {
    id: 11,
    name: "Gloomhaven",
    description: "Epicka kooperacyjna gra przygodowa w świecie mrocznej fantasy z rozbudowaną kampanią.",
    minPlayers: 1,
    maxPlayers: 4,
    minAge: 14,
    playTime: "60-120 min",
    categories: ["Kooperacyjne", "Przygodowe", "Strategiczne"],
    rating: 4.9,
    image: "/images/gloomhaven.jpg",
    year: 2017,
  },
  {
    id: 12,
    name: "Everdell",
    description: "Buduj urocze leśne miasteczko zamieszkałe przez zwierzęta w tej pięknej grze karcianej.",
    minPlayers: 1,
    maxPlayers: 4,
    minAge: 10,
    playTime: "40-80 min",
    categories: ["Strategiczne", "Karciane", "Ekonomiczne"],
    rating: 4.5,
    image: "/images/everdell.jpg",
    year: 2018,
  },
  {
    id: 13,
    name: "Dobble",
    description: "Błyskawiczna gra spostrzegawczości - znajdź pasujący symbol szybciej niż inni!",
    minPlayers: 2,
    maxPlayers: 8,
    minAge: 6,
    playTime: "15 min",
    categories: ["Imprezowe", "Rodzinne"],
    rating: 4.1,
    image: "/images/dobble.jpg",
    year: 2009,
  },
  {
    id: 14,
    name: "Scythe",
    description: "Strategiczna gra osadzona w alternatywnej Europie lat 20. z gigantycznymi robotami.",
    minPlayers: 1,
    maxPlayers: 5,
    minAge: 14,
    playTime: "90-120 min",
    categories: ["Strategiczne", "Wojenne", "Ekonomiczne"],
    rating: 4.7,
    image: "/images/scythe.jpg",
    year: 2016,
  },
  {
    id: 15,
    name: "Kingdomino",
    description: "Prosta gra w budowanie królestwa z mechanizmem domino.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 8,
    playTime: "15 min",
    categories: ["Rodzinne", "Strategiczne"],
    rating: 4.2,
    image: "/images/kingdomino.jpg",
    year: 2016,
  },
  {
    id: 16,
    name: "Wsiąść do Pociągu: Polska",
    description: "Polska edycja kultowej gry - buduj połączenia kolejowe między polskimi miastami.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 8,
    playTime: "30-60 min",
    categories: ["Rodzinne", "Strategiczne"],
    rating: 4.4,
    image: "/images/ticket-poland.jpg",
    year: 2019,
  },
  {
    id: 17,
    name: "Mysterium",
    description: "Kooperacyjna gra dedukcyjna - duch przekazuje wskazówki poprzez wizje, a gracze rozwiązują zagadkę morderstwa.",
    minPlayers: 2,
    maxPlayers: 7,
    minAge: 10,
    playTime: "42 min",
    categories: ["Kooperacyjne", "Dedukcyjne", "Przygodowe"],
    rating: 4.3,
    image: "/images/mysterium.jpg",
    year: 2015,
  },
  {
    id: 18,
    name: "Brass: Birmingham",
    description: "Ekonomiczna gra strategiczna o budowaniu przemysłu w Anglii okresu rewolucji przemysłowej.",
    minPlayers: 2,
    maxPlayers: 4,
    minAge: 14,
    playTime: "60-120 min",
    categories: ["Strategiczne", "Ekonomiczne"],
    rating: 4.8,
    image: "/images/brass.jpg",
    year: 2018,
  },
  {
    id: 19,
    name: "Patchwork",
    description: "Gra dla dwóch osób o szyciu kołdry z różnych kawałków materiału.",
    minPlayers: 2,
    maxPlayers: 2,
    minAge: 8,
    playTime: "15-30 min",
    categories: ["Abstrakcyjne", "Strategiczne"],
    rating: 4.4,
    image: "/images/patchwork.jpg",
    year: 2014,
  },
  {
    id: 20,
    name: "Wingspan",
    description: "Piękna gra o kolekcjonowaniu ptaków w swoich siedliskach. Łączy elementy silnika kart z edukacją przyrodniczą.",
    minPlayers: 1,
    maxPlayers: 5,
    minAge: 10,
    playTime: "40-70 min",
    categories: ["Strategiczne", "Karciane", "Rodzinne"],
    rating: 4.6,
    image: "/images/wingspan.jpg",
    year: 2019,
  },
];
